### ISSUE TITLE
Add submission tutorial (markdown)

### ISSUE THREAD

**Issue by datapolitan** [datapolitan/MiningTheOpenWeb#49]
- [ ] Git pull
- [ ] checkout new branch 
- [ ] Adding content
- [ ] Putting in tags
- [ ] proper markup with CSS
- [ ] committing result
- [ ] git push
- [ ] open pull request

**Comment by oliverpratt** [comment]
![img_6330](https://cloud.githubusercontent.com/assets/16929090/14495208/7b2b6ac2-015c-11e6-9475-862cf5e367f5.jpg)

I chose a topic that has been red hot in my home state for more than a few years now; Legal Marijuana. With legalization comes much more responsibility and consequences for not following the law. Zoning has played an enormous role in the development of 'pot friendly' areas, essentially dictating where we can allow this industry to thrive and how big we want it to get. I decided to use Seattle as an example of how complex the zoning is since it has the most easily accessible data of this kind. 

In the map above, you can see where recreational stores and production facilities are able to open, and where they are not. What this map also does a good job of doing is showing where current medical dispensaries are located in relation to the zoning changes and where medical facilities with proposed expansion plans for new recreational stores would open. However, what this map does a poor job with is visualizing crossed data with key elements that make up prohibited zoning for Marijuana expansion. I am talking about day cares, schools, and other miscellaneous elements. The rest of the data may be good, but comes off to me as being more two dimensional because it does not tell me why there are areas where I could not (theoretically) open up my own shop.

**Comment by datapolitan** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by datapolitan** [comment]
http://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream
